version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: certificatesdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  certificate-service:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/certificatesdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "3003:3003"
    volumes:
      - ./generated-pdfs:/app/generated-pdfs
      - ./src/main/resources/static/certificates:/app/static/certificates

volumes:
  pgdata: