apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-dashboard
  namespace: default
  labels:
    app: university-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-dashboard
  template:
    metadata:
      labels:
        app: university-dashboard
    spec:
      containers:
        - name: university-dashboard
          image: sachintp/university-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
