apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-portal
  template:
    metadata:
      labels:
        app: student-portal
    spec:
      containers:
      - name: student-portal
        image: student-portal:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: student-portal
spec:
  type: ClusterIP
  selector:
    app: student-portal
  ports:
  - port: 3000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-portal
  template:
    metadata:
      labels:
        app: university-portal
    spec:
      containers:
      - name: university-portal
        image: university-portal:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: university-portal
spec:
  type: ClusterIP
  selector:
    app: university-portal
  ports:
  - port: 3001
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employer-portal
  template:
    metadata:
      labels:
        app: employer-portal
    spec:
      containers:
      - name: employer-portal
        image: employer-portal:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: employer-portal
spec:
  type: ClusterIP
  selector:
    app: employer-portal
  ports:
  - port: 3002
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-dashboard
  template:
    metadata:
      labels:
        app: admin-dashboard
    spec:
      containers:
      - name: admin-dashboard
        image: admin-dashboard:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard
spec:
  type: ClusterIP
  selector:
    app: admin-dashboard
  ports:
  - port: 3003
    targetPort: 80