apiVersion: v1
kind: Service
metadata:
  name: verification-service
  labels:
    app: verification-service
spec:
  type: NodePort
  selector:
    app: verification-service
  ports:
    - name: http
      port: 3004         # Cluster IP port
      targetPort: 3004   # Container port
      nodePort: 30044    # NodePort (must be 30000â€“32767)
