apiVersion: v1
kind: ConfigMap
metadata:
  name: verification-config
  labels:
    app: verification-service
data:
  CERTIFICATE_SERVICE_URL: "http://certificate-service:3003"
  UNIVERSITY_SERVICE_URL: "http://university-service:3002"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka"
