apiVersion: v1
kind: Service
metadata:
  name: university-service
  labels:
    app: university-service
spec:
  type: NodePort    # handy for minikube
  selector:
    app: university-service
  ports:
    - name: http
      port: 30032        # cluster port
      targetPort: 3002   # container port
      nodePort: 30086    # optional; can remove to auto-assign
