apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-service
  labels:
    app: university-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-service
  template:
    metadata:
      labels:
        app: university-service
    spec:
      containers:
        - name: university-service
          image: university-service:1.0.0-dev   # local image built inside minikube
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3002
            
          envFrom:
            - configMapRef:
                name: university-service-config
            - secretRef:
                name: university-service-secret
          livenessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
