apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: admin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-dashboard
                port:
                  number: 80
    - host: student.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-dashboard
                port:
                  number: 80
    - host: employer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: employer-dashboard
                port:
                  number: 80
    - host: university.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: university-dashboard
                port:
                  number: 80
