apiVersion: apps/v1
kind: Deployment
metadata:
  name: employer-dashboard
  namespace: default
  labels:
    app: employer-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employer-dashboard
  template:
    metadata:
      labels:
        app: employer-dashboard
    spec:
      containers:
        - name: employer-dashboard
          image: sachintp/employer-dashboard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
