apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  # Used by application.yaml: ${DB_USERNAME:postgres}
  DB_USERNAME: postgres

  # Used by application.yaml: ${DB_PASSWORD:password}
  DB_PASSWORD: postgres

  # Maps to jwt.secret -> JWT_SECRET
  # IMPORTANT: change to a long, random value in real env
  JWT_SECRET: "change-this-to-a-very-long-random-secret-key"
