apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-notification
  template:
    metadata:
      labels:
        app: email-notification
    spec:
      containers:
        - name: email-notification
          image: email-notification:1.0.0-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: email-config
            - secretRef:
                name: email-secret
