apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certificate-postgres
  template:
    metadata:
      labels:
        app: certificate-postgres
    spec:
      containers:
        - name: certificate-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: certificate-postgres-config
            - secretRef:
                name: certificate-postgres-secret
          volumeMounts:
            - name: certificate-postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: certificate-postgres-storage
          persistentVolumeClaim:
            claimName: certificate-postgres-pvc
